### ISSUE TITLE
dailynote无法完全显示图片

### ISSUE THREAD

**Issue by V1stone** [LuciusChen/roam-logseq-themes#1]
dailynote无法完全显示标题的图片，其他页面正常显示
![image](https://user-images.githubusercontent.com/103471916/164952884-da3f433d-b0b6-4fd5-99ca-1b17705d3a45.png)
![image](https://user-images.githubusercontent.com/103471916/164952726-59403dc0-524d-46d1-be0b-e010f395d805.png)

**Comment by LuciusChen** [comment]
这是通过 css 添加到背景图片么？因为我没找到设置中可以添加背景图片的。

**Comment by LuciusChen** [comment]
你把他的 css 改一下，下面圈起来的部分改为：`height: 30vh !important;`，就可以了。
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/4947981/166095136-d4108c1d-6ccd-4e59-a485-ed44a9458b49.png">

如果还要标题的颜色从绿色改为白色，就在我的主题文件里面找到这一段。将颜色的值改为 `#fff` 就可以了。

```
.roam-body .roam-app .roam-main .roam-article h1.rm-title-display {
  color: var(--title-accent-color) !important;
}
```
