### ISSUE TITLE
Roam 中 main window block reference number 无法显示

### ISSUE THREAD

**Issue by liefsun** [LuciusChen/roam-logseq-themes#3]
Roam 中 main window block reference number 无法显示，但是在sidebar就可以正常显示，如图所示
<img width="735" alt="CleanShot 2022-04-27 at 22 41 59@2x" src="https://user-images.githubusercontent.com/48837167/165635945-b13396bc-1a50-4e8d-bbbc-7bda7646e649.png">

<img width="633" alt="CleanShot 2022-04-27 at 22 42 17@2x" src="https://user-images.githubusercontent.com/48837167/165636002-7ec87559-df8c-4f7b-a19a-03fef5e57ecf.png">

**Comment by LuciusChen** [comment]
已修复
